title: Joshua Called Me
description: A classic case for recruitment by the Soviets
permalink: pretty

# Jekyll
paginate: 10
highlighter: rouge
plugins: [jekyll-paginate]
timezone: Europe/London
paginateLabel: page
paginate_path: "page/:num"
