name: Joshua Called Me
description: A classic case for recruitment by the Soviets
permalink: pretty
email: richard@brickdigest.com
author: Richard Smith
lang: en
locale: en_GB

# Jekyll
paginate: 10
highlighter: rouge
plugins: [jekyll-paginate]
timezone: Europe/London
paginateLabel: page
paginate_path: "page/:num"
baseurl: https://richardsmith.me